### PR TITLE
Cleanup hardcoded clientID

### PR DESCRIPTION
**Pull request by roblack**
Not sure if this was left by accident?

### CODE REVIEW

**Review by daneden — CHANGES_REQUESTED** [review]
Nice catch! Confusingly, the client ID is actually different from the API key. You can find the client ID on the Keys & Tokens page in the Twitter developer portal. I plan to try and document this nuance somewhere.

**Comment by daneden** [comment]
@roblack yep, that's right! It’ll need adding to the .env.example and the pre-action build script which you can find in Xcode’s Scheme Editor. If I get time later I can work on this myself.

**Comment by roblack** [comment]
Hm...I tried to find it but not really sure this is it. When I inspected the scheme I did not find any scripts I could ament. 🤷‍♂️

**Review by daneden — APPROVED** [review]

**Comment by daneden** [comment]
Committed on your branch, that should do the trick!

**Pull request merged**
